language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"

script:
  - npm run build

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage